apiVersion: v1
kind: Service
metadata:
  name: pokemon
spec:
  type: LoadBalancer
  ports:
    - port: 80           # Exposes port 80 externally
      targetPort: 8080    # Forwards traffic to container port 8080
  selector:
    app: springboot
