name: build-pokemon
on:
  push:
    branches:
      - main
      - prd
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: setup jdk-17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: build with mvn
        run: ./mvn clean install
     
    
